[package]
name = "lxc"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
clap = { version = "4.5.50", features = ["derive"] }
logos = "0.15.1"
colored = "3.0.0"
